---

# Variables definition
# Pycharm, target and working directories: C:\Users\victorm\PycharmProjects\pythonProject1\auto
# set working dir below to be same as this
dirs:
  working: !!str "C:\\Users\\victorm\\PycharmProjects\\pythonProject1\\auto\\"  # note above wrt PyCharm working + target directories
  
urls:
  AWE: !!str "https://wfo.a31.verintcloudservices.com/wfo/control/signin"       # SSO logon Tenant admin T1
  AWE_dash: !!str "https://wfo.a31.verintcloudservices.com/wfo/ui"              # used after initial login context saved
  AWE_T0: !!str "https://wfo.a31.verintcloudservices.com/wfo/control/dbrealmsignin"     # dbrealm signin, T0

# AWE credentials tenant admin, T0 admin
logon:
  USERNAME_TA : !!str "admin01@verintnew01.prodreleasev2.com"     # tenant admin
  PASSWORD_TA : !!str "Verint.123!!"
  USERNAME_T0 : !!str "admin01@avaya.com"     # tenant admin
  PASSWORD_T0 : !!str "1_Abc_123"

logs:
  log_level : !!str "DEBUG" # all capital letters required for this field
  
output_files:
  dump_screenshots : !!bool TRUE # dump search screens to png
  dump_xml : !!bool TRUE   # dump outerHTML to xml
  output_xml : !!str "output_xml.xml" # dump search page xml
  log_out : !!str "_checkAWE.log"     # log file name
  out_csv : !!str "file_recSearchResultsOuter.csv"    # output recordings search dumped to csv
  output_prefix_path : !!str "output\\"        # where to dump all output files incl csv, log files etc
  output_prefix_path_old : !!str "old\\"        # where to store all old output files incl csv, log files etc in 'output_prefix_path' folder
  output_inner_html : !!str "capture_RecTablesInnerhtml.xml"   # dump file for search menu > innerhtml
  output_text_dump : !!str "output_textdump-rec.txt"   # text file to dump search page
  dump_text : !!bool TRUE
  dump_csv : !!bool TRUE
  CaptureVerification_csv : !!str "CaptureVerification"    # output subdirectory where doAutomated Capture Verification zip downloaded 
  
screenshots:
  interactions_menu_screenshot : !!str "interactionsMenu_screen.png"      # screenshot name for interactions menu
  recordings_default_screen : !!str "screenshot_RecordingsDefaultSearch.png" # screenshot name for search recordings
  
waits:
  driver_wait_sec : !!int 30  # wait time in seconds until elements are available on the webpage, otherwise timeout exception occurs
  
chromedriver:
  path_to_chrome : !!str 'drivers/chromedriver.exe'       # no longer required with webdriver-manager
  UseWebdriver_manager: !!str 'FALSE'            # if set to TRUE uses webdriver_manager to set up selenium driver, otherwise uses in-situ Chrome webdriver and path_to_chrome installation option

# search string in recordings search menu results  
search:
  search_string : !!str "08/15/2023"      # search by particular date, formT mm/dd/yyyy
  user_search : !!str "user007@verintnew01.prodreleasev2.com" # CCaaS user format e.g. "user007@verintnew01.prodreleasev2.com"
  any_string : !!str "user007"
  
swversion:
  logon: !!str "Version: 15.2 (15.2.1024.728)"
  integration_server: !!str "'Version: 15.2 (15.2.1014.390)'"
    
search_calls:
  number_rows: !!int 0      # number of recorded calls found
  CaptVerif_callsFound: !!int 0     # number of recorded calls found with Capture Verification issues
        
viewport_size:
  width: !!int 1900
  height: !!int 1300

# T0 admin tests, tests requiring T0 webpage access, caps "YES" or "NO"
T0_to_test:
  test_1: !!str "YES"
  test_2: !!str "YES"
  test_3: !!str "YES"
  test_4: !!str "YES"
  test_5: !!str "YES"
  test_6: !!str "YES"
  test_7: !!str "YES"
  test_8: !!str "YES"
  test_9: !!str "YES"
  test_10: !!str "YES"
  test_11: !!str "YES"   
  test_12: !!str "YES"   
 
# T1 tenant admin tests , tests requiring T1 tenant admin access
T1_to_test:
  test_1: !!str "YES"
  test_2: !!str "YES"
  test_3: !!str "YES"
  test_4: !!str "YES"
  test_5: !!str "YES"
  test_6: !!str "YES"
  test_7: !!str "YES"
  test_8: !!str "YES"
  test_9: !!str "YES"
  test_10: !!str "YES"
  test_11: !!str "YES"   
  test_12: !!str "YES"
  test_13: !!str "YES"   
  test_14: !!str "YES"
  
# T1 tenant admin captureVerification tests , tests requiring T1 tenant admin access
T1CaptVerif_to_test:
  test_1: !!str "YES"
  test_2: !!str "YES"
  test_3: !!str "YES"
  test_4: !!str "YES"
  test_5: !!str "YES"
  test_6: !!str "YES"
  test_7: !!str "YES"
  test_8: !!str "YES"
  
search_days:
  days: !!int 1     # number of days to search for in search and relay

# LOG LEVELS
# Level	Numeric Value	Description
# Critical	50	Highest severity messages; may cause a program to crash or exit.
# Error	40	High severity messages generally related to an operation failing that does not cause the program to crash or exit.
# Warning	30	Potentially negative events that may cause abnormal operation or otherwise require attention (such as the use of a deprecated API).
# Info	20	Messages that log standard/expected events.
# Debug	10	Messages useful for debugging how an application is running.
# Notset	0	Default level when a new logger is created. Setting the root logger to NOTSET logs all messages. For other loggers, NOTSET messages are delegated to parent loggers until a level other than NOTSET is found.

#T1 tests:
#1: SignOnWebpageTitle
#2: Usernnme_logon_filed_available
#3: WFO_Version_frontPage
#4: Tenant_admin_signin
#5: accessInteractionsSearchPage
#6: searchCallsLast7d
#7: searchCallFromToday 
#8: searchCallDateString ( defined config.yaml)
#9: searchCallUserString ( defined config.yaml)
#10: logout

#T0 tests:
#1: SignOnWebpageTitle
#2: Usernnme_logon_filed_available
#3: WFO_Version_frontPage
#4: Tenant_admin_signin